_GN = "https://news.google.com/rss/search?hl=pt-BR&gl=BR&ceid=BR:pt-419&q="

SOURCES = [
    {
        "id": "bcb",
        "name": "Banco Central do Brasil",
        "category": "Banco Central",
        "icon": "🏦",
        "rss_url": "https://www.bcb.gov.br/api/feed/sitemap/noticias.xml",
    },
    {
        "id": "tesouro",
        "name": "Tesouro Nacional",
        "category": "Fiscal",
        "icon": "🏛️",
        "rss_url": _GN + "Tesouro+Nacional+resultado+fiscal+divida",
    },
    {
        "id": "fazenda",
        "name": "Ministerio da Fazenda",
        "category": "Fiscal",
        "icon": "📊",
        "rss_url": _GN + "Ministerio+da+Fazenda+economia+fiscal",
    },
    {
        "id": "receita",
        "name": "Receita Federal",
        "category": "Fiscal",
        "icon": "📋",
        "rss_url": _GN + "Receita+Federal+arrecadacao+tributos",
    },
    {
        "id": "camara",
        "name": "Camara dos Deputados",
        "category": "Legislativo",
        "icon": "🏛️",
        "rss_url": "https://www.camara.leg.br/noticias/rss/ultimas",
    },
    {
        "id": "senado",
        "name": "Senado Federal",
        "category": "Legislativo",
        "icon": "🏛️",
        "rss_url": "https://www12.senado.leg.br/noticias/rss/ultimas",
    },
    {
        "id": "stf",
        "name": "STF",
        "category": "Judiciario",
        "icon": "⚖️",
        "rss_url": "https://portal.stf.jus.br/servicos/rss/noticias.asp",
    },
    {
        "id": "cvm",
        "name": "CVM",
        "category": "Regulatorio",
        "icon": "📜",
        "rss_url": _GN + "CVM+comissao+valores+mobiliarios+instrucao",
    },
    {
        "id": "anbima",
        "name": "ANBIMA",
        "category": "Regulatorio",
        "icon": "📐",
        "rss_url": _GN + "ANBIMA+mercado+capitais+regulamento",
    },
    {
        "id": "b3",
        "name": "B3",
        "category": "Bolsa",
        "icon": "📈",
        "rss_url": _GN + "B3+bolsa+valores+comunicado+regulatorio",
    },
    {
        "id": "vale",
        "name": "Vale (VALE3)",
        "category": "Mineracao",
        "icon": "⛏️",
        "rss_url": _GN + "Vale+S.A.+resultado+fato+relevante",
    },
    {
        "id": "petrobras",
        "name": "Petrobras (PETR4)",
        "category": "Energia",
        "icon": "🛢️",
        "rss_url": _GN + "Petrobras+resultado+fato+relevante",
    },
    {
        "id": "itau",
        "name": "Itau Unibanco (ITUB4)",
        "category": "Financeiro",
        "icon": "🏦",
        "rss_url": _GN + "Itau+Unibanco+resultado+trimestral",
    },
    {
        "id": "bradesco",
        "name": "Bradesco (BBDC4)",
        "category": "Financeiro",
        "icon": "🏦",
        "rss_url": _GN + "Bradesco+resultado+trimestral+fato+relevante",
    },
    {
        "id": "ambev",
        "name": "Ambev (ABEV3)",
        "category": "Consumo",
        "icon": "🍺",
        "rss_url": _GN + "Ambev+resultado+trimestral+fato+relevante",
    },
    {
        "id": "suzano",
        "name": "Suzano (SUZB3)",
        "category": "Papel e Celulose",
        "icon": "🌲",
        "rss_url": _GN + "Suzano+papel+celulose+resultado",
    },
    {
        "id": "klabin",
        "name": "Klabin (KLBN11)",
        "category": "Papel e Celulose",
        "icon": "📦",
        "rss_url": _GN + "Klabin+resultado+trimestral+fato+relevante",
    },
    {
        "id": "bb",
        "name": "Banco do Brasil (BBAS3)",
        "category": "Financeiro",
        "icon": "🏦",
        "rss_url": _GN + "Banco+do+Brasil+resultado+trimestral",
    },
]

RELEVANCE_KEYWORDS = [
    "resultado", "lucro", "prejuizo", "receita", "ebitda", "dividendo",
    "juro", "selic", "inflacao", "ipca", "pib", "cambio", "dolar",
    "fato relevante", "ipo", "emissao", "debenture",
    "taxa", "fiscal", "divida", "arrecadacao", "superavit", "deficit",
    "earnings", "revenue", "profit", "loss", "guidance", "rating",
    "producao", "exportacao", "operacao", "capex", "investimento",
    "regulacao", "instrucao", "deliberacao", "resolucao", "portaria",
]       