"""
Fontes oficiais de notícias e atos regulatórios para o NewsBot.

Compatível com o main.py atual:
- cada item de SOURCES precisa ter rss_url
- o parsing é feito por feedparser no main.py
"""

SOURCES = [
    # CVM
    {
        "id": "cvm_decisoes",
        "name": "CVM — Decisões do Colegiado",
        "category": "Regulatório",
        "rss_url": "http://www.cvm.gov.br/feed/decisoes.xml",
    },
    {
        "id": "cvm_legislacao",
        "name": "CVM — Legislação",
        "category": "Regulatório",
        "rss_url": "http://www.cvm.gov.br/feed/legislacao.xml",
    },
    {
        "id": "cvm_sancionadores",
        "name": "CVM — Processos Sancionadores",
        "category": "Regulatório",
        "rss_url": "http://www.cvm.gov.br/feed/sancionadores.xml",
    },
    {
        "id": "cvm_despachos",
        "name": "CVM — Despachos",
        "category": "Regulatório",
        "rss_url": "http://www.cvm.gov.br/feed/despachos.xml",
    },
    {
        "id": "cvm_audiencias",
        "name": "CVM — Audiências Públicas",
        "category": "Regulatório",
        "rss_url": "http://www.cvm.gov.br/feed/audiencias.xml",
    },
    {
        "id": "cvm_informativos",
        "name": "CVM — Informativos do Colegiado",
        "category": "Regulatório",
        "rss_url": "http://www.cvm.gov.br/feed/informativos_colegiado.xml",
    },

    # Gov.br
    {
        "id": "gov_noticias",
        "name": "Gov.br — Notícias",
        "category": "Fiscal",
        "rss_url": "https://www.gov.br/pt-br/noticias/RSS",
    },
    {
        "id": "gov_rss_noticias",
        "name": "Gov.br — RSS Notícias",
        "category": "Fiscal",
        "rss_url": "https://www.gov.br/pt-br/rss/colecoes-de-rss/rss-noticias/RSS",
    },
    {
        "id": "gov_financas",
        "name": "Gov.br — Finanças, Impostos e Gestão Pública",
        "category": "Fiscal",
        "rss_url": "https://www.gov.br/pt-br/noticias/financas-impostos-e-gestao-publica/RSS",
    },
]

RELEVANCE_KEYWORDS = [
    # Política monetária / inflação
    "copom",
    "selic",
    "juros",
    "taxa de juros",
    "política monetária",
    "politica monetaria",
    "inflação",
    "inflacao",
    "ipca",
    "ipca-15",
    "igp-m",
    "igp",
    "focus",
    "boletim focus",

    # Mercado de capitais / regulação
    "cvm",
    "mercado de capitais",
    "oferta pública",
    "oferta publica",
    "oferta",
    "debênture",
    "debentures",
    "debêntures",
    "debenture",
    "securitização",
    "securitizacao",
    "fii",
    "fiagro",
    "fundo de investimento",
    "fundos de investimento",
    "cri",
    "cra",
    "ipo",
    "follow-on",
    "companhia aberta",
    "valores mobiliários",
    "valores mobiliarios",
    "ações",
    "acoes",

    # Crédito / bancário
    "crédito",
    "credito",
    "spread bancário",
    "spread bancario",
    "spread",
    "inadimplência",
    "inadimplencia",
    "sistema financeiro",
    "banco central",
    "bancos",
    "bancário",
    "bancario",
    "tesouro direto",
    "tesouro nacional",
    "curva de juros",

    # Fiscal / arrecadação / governo
    "fiscal",
    "arcabouço fiscal",
    "arcabouco fiscal",
    "resultado primário",
    "resultado primario",
    "meta fiscal",
    "superávit",
    "superavit",
    "déficit",
    "deficit",
    "arrecadação",
    "arrecadacao",
    "receita federal",
    "ministério da fazenda",
    "ministerio da fazenda",
    "tributário",
    "tributario",
    "tributária",
    "tributaria",
    "imposto de renda",
    "iof",
    "pis",
    "cofins",
    "csll",
    "reforma tributária",
    "reforma tributaria",
    "orçamento",
    "orcamento",
    "gasto público",
    "gasto publico",
    "dívida pública",
    "divida publica",

    # Macro / atividade / IBGE
    "ibge",
    "pib",
    "pnad",
    "pnad contínua",
    "pnad continua",
    "produção industrial",
    "producao industrial",
    "varejo",
    "serviços",
    "servicos",
    "desemprego",
    "renda",
    "massa salarial",
    "balança comercial",
    "balanca comercial",
    "safra",
    "agropecuária",
    "agropecuaria",

    # Empresas / resultados
    "resultado",
    "lucro",
    "prejuízo",
    "prejuizo",
    "ebitda",
    "guidance",
    "dividendos",
    "dividendo",
    "jcp",
    "juros sobre capital próprio",
    "juros sobre capital proprio",
    "margem",
    "receita líquida",
    "receita liquida",
    "captação",
    "captacao",
    "emissão",
    "emissao",

    # Internacional
    "fed",
    "fomc",
    "bce",
    "ecb",
    "treasury",
    "china",
    "estados unidos",
    "dólar",
    "dolar",
    "câmbio",
    "cambio",
    "commodities",
    "petróleo",
    "petroleo",
]

IRRELEVANT_HINTS = [
    "aniversário",
    "aniversario",
    "campanha institucional",
    "evento interno",
    "seminário comemorativo",
    "seminario comemorativo",
    "premiação",
    "premiacao",
    "agenda cultural",
]