"""
Fontes oficiais de notícias e atos regulatórios para o NewsBot.

Compatível com o main.py atual:
- cada item de SOURCES precisa ter rss_url
- o parsing é feito por feedparser no main.py
"""

SOURCES = [
    # CVM — manter apenas feeds com maior potencial de relevância para mercado
    {
        "id": "cvm_decisoes",
        "name": "CVM — Decisões do Colegiado",
        "category": "Regulatório",
        "rss_url": "http://www.cvm.gov.br/feed/decisoes.xml",
    },
    {
        "id": "cvm_sancionadores",
        "name": "CVM — Processos Sancionadores",
        "category": "Regulatório",
        "rss_url": "http://www.cvm.gov.br/feed/sancionadores.xml",
    },
    {
        "id": "cvm_audiencias",
        "name": "CVM — Audiências Públicas",
        "category": "Regulatório",
        "rss_url": "http://www.cvm.gov.br/feed/audiencias.xml",
    },

    # Atenção:
    # Removi temporariamente:
    # - cvm_legislacao
    # - cvm_despachos
    # - cvm_informativos
    #
    # Motivo:
    # Esses feeds estão trazendo muitos ofícios, despachos e orientações operacionais.
    # Podemos reativar depois com filtro específico por fonte.

    # Gov.br
    {
        "id": "gov_financas",
        "name": "Gov.br — Finanças, Impostos e Gestão Pública",
        "category": "Fiscal",
        "rss_url": "https://www.gov.br/pt-br/noticias/financas-impostos-e-gestao-publica/RSS",
    },
]

RELEVANCE_KEYWORDS = [
    # Política monetária / inflação
    "copom",
    "selic",
    "juros",
    "taxa de juros",
    "política monetária",
    "politica monetaria",
    "inflação",
    "inflacao",
    "ipca",
    "ipca-15",
    "igp-m",
    "igp",
    "focus",
    "boletim focus",

    # Mercado de capitais / regulação
    # IMPORTANTE: não colocar apenas "cvm", senão qualquer item da CVM passa no filtro.
    "mercado de capitais",
    "oferta pública",
    "oferta publica",
    "oferta",
    "debênture",
    "debentures",
    "debêntures",
    "debenture",
    "securitização",
    "securitizacao",
    "fii",
    "fiagro",
    "fidc",
    "fundo de investimento",
    "fundos de investimento",
    "cri",
    "cra",
    "ipo",
    "follow-on",
    "opa",
    "companhia aberta",
    "companhias abertas",
    "emissor de valores mobiliários",
    "emissores de valores mobiliários",
    "valores mobiliários",
    "valores mobiliarios",
    "ações",
    "acoes",
    "acionistas",
    "administrador de carteira",
    "gestor de recursos",
    "consultor de valores mobiliários",
    "analista de valores mobiliários",
    "processo administrativo sancionador",
    "processo sancionador",
    "termo de compromisso",
    "multa",
    "condenação",
    "condenacao",
    "insider trading",
    "manipulação de mercado",
    "manipulacao de mercado",
    "fraude",
    "colegiado",
    "decisão do colegiado",
    "decisao do colegiado",
    "resolução cvm",
    "resolucao cvm",
    "consulta pública",
    "consulta publica",
    "audiência pública",
    "audiencia publica",

    # Crédito / bancário
    "crédito",
    "credito",
    "spread bancário",
    "spread bancario",
    "spread",
    "inadimplência",
    "inadimplencia",
    "sistema financeiro",
    "banco central",
    "bancos",
    "bancário",
    "bancario",
    "tesouro direto",
    "tesouro nacional",
    "curva de juros",

    # Fiscal / arrecadação / governo
    "fiscal",
    "arcabouço fiscal",
    "arcabouco fiscal",
    "resultado primário",
    "resultado primario",
    "meta fiscal",
    "superávit",
    "superavit",
    "déficit",
    "deficit",
    "arrecadação",
    "arrecadacao",
    "receita federal",
    "ministério da fazenda",
    "ministerio da fazenda",
    "tributário",
    "tributario",
    "tributária",
    "tributaria",
    "imposto de renda",
    "iof",
    "pis",
    "cofins",
    "csll",
    "reforma tributária",
    "reforma tributaria",
    "orçamento",
    "orcamento",
    "gasto público",
    "gasto publico",
    "dívida pública",
    "divida publica",

    # Macro / atividade / IBGE
    "ibge",
    "pib",
    "pnad",
    "pnad contínua",
    "pnad continua",
    "produção industrial",
    "producao industrial",
    "varejo",
    "serviços",
    "servicos",
    "desemprego",
    "renda",
    "massa salarial",
    "balança comercial",
    "balanca comercial",
    "safra",
    "agropecuária",
    "agropecuaria",

    # Empresas / resultados
    "resultado",
    "lucro",
    "prejuízo",
    "prejuizo",
    "ebitda",
    "guidance",
    "dividendos",
    "dividendo",
    "jcp",
    "juros sobre capital próprio",
    "juros sobre capital proprio",
    "margem",
    "receita líquida",
    "receita liquida",
    "captação",
    "captacao",
    "emissão",
    "emissao",

    # Internacional
    "fed",
    "fomc",
    "bce",
    "ecb",
    "treasury",
    "china",
    "estados unidos",
    "dólar",
    "dolar",
    "câmbio",
    "cambio",
    "commodities",
    "petróleo",
    "petroleo",
]

IRRELEVANT_HINTS = [
    # Institucional / eventos
    "aniversário",
    "aniversario",
    "campanha institucional",
    "evento interno",
    "seminário comemorativo",
    "seminario comemorativo",
    "premiação",
    "premiacao",
    "agenda cultural",
    "curso",
    "capacitação",
    "capacitacao",
    "workshop",
    "webinário",
    "webinario",
    "seminário",
    "seminario",
    "encontro",
    "reunião",
    "reuniao",

    # CVM — ruído operacional / administrativo
    "ofício circular",
    "oficio circular",
    "ofícios circulares",
    "oficios circulares",
    "descontinuidade do endereço",
    "descontinuidade de endereço",
    "endereço https",
    "endereco https",
    "sistema empresas.net",
    "empresas.net",
    "sistema enet",
    "enet",
    "sistema fundos.net",
    "fundos.net",
    "sistema cvm",
    "indisponibilidade",
    "manutenção",
    "manutencao",
    "instabilidade",
    "atualização de sistema",
    "atualizacao de sistema",
    "manual de preenchimento",
    "orientações às entidades administradoras",
    "orientacoes as entidades administradoras",
    "orientação às entidades administradoras",
    "orientacao as entidades administradoras",
    "registro inicial de emissor",
    "companhias de menor porte",
    "formulário cadastral",
    "formulario cadastral",
    "formulário de referência",
    "formulario de referencia",
    "entrega de documentos",
    "prazo para envio",
    "prazo de envio",
    "instruções de preenchimento",
    "instrucoes de preenchimento",

    # Gov.br — ruído geral
    "ministro participa",
    "ministra participa",
    "governo participa",
    "cerimônia",
    "cerimonia",
    "assinatura de acordo",
    "acordo de cooperação",
    "acordo de cooperacao",
    "nota de pesar",
    "posse",
    "nomeação",
    "nomeacao",
]
